package com.kakaocert.api.test.util;

import java.io.UnsupportedEncodingException;

import javax.xml.bind.DatatypeConverter;

public class decodeBase64Url {

	public static String run(String arg) {
		byte[] result = DatatypeConverter.parseBase64Binary(arg);
		String resultStr = "";
		try {
			resultStr =  new String(result,"UTF-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return resultStr;
	}
	
	public static void main(String[] args) {
		
		String result =	decodeBase64Url.run("MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwGggCSABIIBKgoKCnwtLS18LS0tfAp87ZqM7IKs66qFfOqzteyduOyduOymneyEvO2EsHwKfOuCqeu2gOyekOuyiO2YuHzsi53rs4TsvZTrk5x8CnzsmIjquIjso7wo66qF7J2Y7J6QKeuqhXzsmIjquIjso7zrqoV8Cnzsg53rhYTsm5Tsnbx8MTk4OC0wMy0wMXwKfOydgO2WiSjsubTrk5zsgqwp66qFfOq1reuvvOydgO2WiXwKfOqzhOyijCjsubTrk5wp67KI7Zi4fOqzhOyijOuyiO2YuHwKfOyEnOuqheyekHzstZzsg4HtmIF8CgogICAgCgo8IS0tIHxmZDNhNjliZTE0NWM0Y2RkOTY5YzVlZjNlNDdmYzgzZHwxNjE0OTI5ODMwMDAwfCAtLT4AAAAAAACggDCCAi0wggHSoAMCAQICEQCcgG_Ib5NDB4lqG2QNI29kMAoGCCqGSM49BAMCMG0xCzAJBgNVBAYTAktSMRQwEgYDVQQKDAtLYWthbyBDb3JwLjErMCkGA1UECwwiMUhxamJLeFNEb2dTR0FlV2ZBSnNoMW03b0F1OEhZaG1ZZzEbMBkGA1UEAwwSS2FrYW8gQ2VydCBDQSAtIEMxMB4XDTIxMDMwMjE1MDAwMFoXDTIzMDMwMzE0NTk1OVowZjESMBAGA1UEAwwJ7LWc7IOB7ZiBMVAwTgYKCZImiZPyLGQBAQxAY2Q1ZTU5NWFmZjk1YTgxMDBiYjEzZTVhZmRhMjc4YzBjNzUzYjJiMWRlMTkwYWMwMDBhZmJiYTkxNjYzZDAzZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJbnKaxVfrIuId249ScpDchXqTFCG3fcj3EIWF0qDWSff6wY6JZcwRtH8CllPBhnVg7rN72vcQjGMh8T0EkE1jyjWjBYMAkGA1UdEwQCMAAwDgYDVR0PAQH_BAQDAgeAMDsGCCsGAQUFBwEBBC8wLTArBggrBgEFBQcwAYYfaHR0cHM6Ly9jZXJ0Lmtha2FvLmNvbS9wa2kvb2NzcDAKBggqhkjOPQQDAgNJADBGAiEA-xJpw5fMUexZJ2wUW5fFIOnDNzipkdVqWBoN6xFuSDUCIQCPglfKfCF9oUBhLfWeNFQ-3dMzf1CR5snc2OnOZc-ZRgAAMYHuMIHrAgEBMIGCMG0xCzAJBgNVBAYTAktSMRQwEgYDVQQKDAtLYWthbyBDb3JwLjErMCkGA1UECwwiMUhxamJLeFNEb2dTR0FlV2ZBSnNoMW03b0F1OEhZaG1ZZzEbMBkGA1UEAwwSS2FrYW8gQ2VydCBDQSAtIEMxAhEAnIBvyG-TQweJahtkDSNvZDANBglghkgBZQMEAgEFADAKBggqhkjOPQQDAgRGMEQCIFsxRcKTiLjEcA-Yqj85ywAJnGuBWVd0DgaraE98QkQUAiBcH2CqsSnkruNje-HHMgLqQtBPohn1Cw2x5shmnDIyhwAAAAAAAA");
		System.out.println(result);
	}
}

